### ISSUE TITLE
NullPointerException when changing runway when "runway in use" is already selected

### ISSUE THREAD

**Issue by adelaidaCreosteanu** [ElliotAlexander/Runway_Redeclaration_Tool#10]
## Expected behaviour
When selecting a different runway, the view should be updated with the default left virtual runway.

## Current behaviour
The canvas goes white and an exception is thrown in the console. However, the application does not crash, therefore this bug is not critical.

## Possible solution
Track down the bug by following the execution path after the user changes the runway.

## Steps to reproduce
1. Pick airport (one with more than one physical runway)
2. Pick runway
3. Pick runway in use
4. Pick another runway

## Possible implementation
I don't expect this to be a difficult issue to solve. The difficult part is spotting where the problem happens. I suspect that when the user selects a different runway, the application attempts to update the view but cannot find a virtual runway? We must ensure a default one is selected.

**Comment by ElliotAlexander** [comment]
@adelaidaCreosteanu  I've rewritten MainWindowController, as well as the updating system and handled most of these errors. I think this is now closable?

**Comment by adelaidaCreosteanu** [comment]
Nicely done! This is awesome
