### ISSUE TITLE
New Runway Window button is unresponsive when no airport is added.

### ISSUE THREAD

**Issue by ElliotAlexander** [ElliotAlexander/Runway_Redeclaration_Tool#3]
Can we generate a popup window to say 'Add an airport before adding a runway' or suchalike?

**Comment by adelaidaCreosteanu** [comment]
In case the user tries to add a runway before adding an airport?

**Comment by ElliotAlexander** [comment]
Yep! Small thing but some feedback to the user would be good.

**Comment by ElliotAlexander** [comment]
Closed with #ccf2663
